# Generated by Django 5.0.6 on 2024-06-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subir_archivo_e_imagen', '0003_alter_subirdumentoimagen_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubirDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': '¨files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='SubirDumentoImagen',
        ),
    ]
