# Generated by Django 5.0.6 on 2024-06-12 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subir_archivo_e_imagen', '0005_alter_subirdocumento_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subirdocumento',
            table='¨files',
        ),
    ]
